### ISSUE TITLE
Moonraker : Unable to load component: (database)

### ISSUE THREAD

**Issue by AktasC** [dimalo/klipper-web-control-docker#11]
Hello there 👋 

First of all, thanks for your work  
I've been trying to install & run this stack but here are the different errors I kept getting :   

```bash
klipper    | [moonraker.py:load_component()] - Unable to load component: (database)
klipper    | Traceback (most recent call last):
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 200, in load_component
klipper    |     component = load_func(config)
klipper    |   File "/home/klippy/moonraker/moonraker/components/database.py", line 518, in load_component
klipper    |     return MoonrakerDatabase(config)
klipper    |   File "/home/klippy/moonraker/moonraker/components/database.py", line 74, in __init__
klipper    |     os.mkdir(self.database_path)
klipper    | PermissionError: [Errno 13] Permission denied: '/home/klippy/.moonraker/database'
klipper    | [moonraker.py:main()] - Moonraker Error
klipper    | Traceback (most recent call last):
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 200, in load_component
klipper    |     component = load_func(config)
klipper    |   File "/home/klippy/moonraker/moonraker/components/database.py", line 518, in load_component
klipper    |     return MoonrakerDatabase(config)
klipper    |   File "/home/klippy/moonraker/moonraker/components/database.py", line 74, in __init__
klipper    |     os.mkdir(self.database_path)
klipper    | PermissionError: [Errno 13] Permission denied: '/home/klippy/.moonraker/database'
klipper    | 
klipper    | During handling of the above exception, another exception occurred:
klipper    | 
klipper    | Traceback (most recent call last):
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 755, in main
klipper    |     server = Server(app_args, file_logger)
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 138, in __init__
klipper    |     self._load_components(config)
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 176, in _load_components
klipper    |     self.load_component(config, component)
klipper    |   File "/home/klippy/moonraker/moonraker/moonraker.py", line 206, in load_component
klipper    |     raise ServerError(msg)
klipper    | utils.ServerError: Unable to load component: (database)
klipper    | [moonraker.py:main()] - Server Shutdown
klipper    | 2021-07-11 23:42:21,495 INFO exited: moonraker (exit status 1; not expected)
```  
- I didn't test the repo as-is beforehand so I also tried to `git restore *` before a `docker-compose pull && docker-compose up`.  
  - Unfortunately resulted in the same issue.  
- I decided I didn't need Mainsail so I uncommented the `build` part for Fluidd and commented the whole Mainsail part.  
  - Same result

I've also seen the #3 issue so I decided to try and run a shell to `chmod 664` as advised and this specific error disappeared.
But, here's the funny part, now the issue seems to be another EACCESS but somewhere else.   
The message I keep getting over and over :   

```bash
klipper    | 2021-07-11 23:48:08,240 INFO spawned: 'klipper' with pid 10
klipper    | supervisor: couldn\'t exec /home/klippy/klippy-env/bin/python: EACCES
klipper    | supervisor: child process was not spawned
klipper    | 2021-07-11 23:48:08,246 INFO exited: klipper (exit status 127; not expected)
```

Since everything happens in volumes built by the different Dockerfiles, aren't permissions supposed to be "good to go" by default ?   
Also, there are some warnings caused by pip installing as root so I'm wondering if that might be the source 🤔  

---------------

Setup : 
- Docker
- Docker-Compose
- Portainer
- Ubuntu 20.04

**Comment by AktasC** [comment]
After investigating a bit more I've found an underlying issue : 
`/home/klippy/.moonraker` is owned by root, a simple `chown klippy:klippy /home/klippy/.moonraker` fixed it.  

Now Mainsail works but Fluidd still can't communicate with Moonraker.

**Comment by dimalo** [comment]
Thanks for your thorough investigation!
yep sorry for that, I might have forgotten to change the supplied moonraker config. There the correct db path should be .moonraker_database
I changed this on behalf of moonraker example config stating it should be kept separate to other moonraker data but forgot to update the config.
the path prepared in the Docker image matches the example shown [here](https://moonraker.readthedocs.io/en/latest/configuration/)

**Comment by dimalo** [comment]
Those two COPY ops are by intent as root. It's not always a bad thing :)

Please have a look into the logs with docker-compose logs -f or similar. Is there anything about the mcu?
Seems like you really did a great job on fixing your issues, but now it's more of a communication issue.
The only problem with docker containers and communication I experienced so far was mismatched group permissions.
Fixed it by introducing argument based config in docker-compose.yml
      # args:
      #   DEVICE_GROUP: device
      #   DEVICE_GID: 987

But I'm pretty sure you checked already right?

**Comment by AktasC** [comment]
> Those two COPY ops are by intent as root. It's not always a bad thing :)
> 
> Please have a look into the logs with docker-compose logs -f or similar. Is there anything about the mcu?
> Seems like you really did a great job on fixing your issues, but now it's more of a communication issue.
> The only problem with docker containers and communication I experienced so far was mismatched group permissions.
> Fixed it by introducing argument based config in docker-compose.yml
> # args:
> # DEVICE_GROUP: device
> # DEVICE_GID: 987
> 
> But I'm pretty sure you checked already right?
> 
> I would be interested if you can make sure if the mcu is actually running...

Thanks for your answer and potential leads  

I tried with the args for `DEVICE_GROUP` & `DEVICE_GID`, unfortunately it didn't change anything.  

I've scouted the logs but the only error message I get besides `systemctl` not being available is this one :  
``` 
[moonraker.py:_check_ready()] - ,
Printer is not ready,
The klippy host software is attempting to connect.  Please,
retry in a few moments.
```

Also, `sudo systemctl list-units | grep active` returns a loaded and active `ttyUSB0-tty-ttyUSB0.device`

**Comment by dimalo** [comment]
https://discord.gg/8UcjUuf6

**Comment by ahalekelly** [comment]
I just pulled the latest version of the git repo and am also getting this error now. Did you guys ever figure it out? That discord invite is expired.

**Comment by dimalo** [comment]
@ahalekelly check the moonraker config. I just pushed a change to align .moonraker_database with the touched file in the Dockerfile. Sorry for the inconvenience, wanted to stick to what moonraker docs suggest...

**Comment by ahalekelly** [comment]
Great, thanks! It's working for me again. Looks like you forgot to make this update in docker-compose.yml though?
